architectury {
    common rootProject.enabled_platforms.split(',')
}

loom {
    accessWidenerPath = file("src/main/resources/${rootProject.archives_name}.accesswidener")
}

repositories {
    maven {
        url = "https://www.cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }
}

dependencies {
    modImplementation "net.fabricmc:fabric-loader:$rootProject.fabric_loader_version"
    modImplementation "com.cobblemon:mod:$rootProject.cobblemon_version"
    api("fuzs.forgeconfigapiport:forgeconfigapiport-common-neoforgeapi:$rootProject.forge_config_api_version")
    modCompileOnly "com.terraformersmc:modmenu:11.0.3"

    modCompileOnly "curse.maven:radical-cobblemon-trainers-api-1152792:8876927"

    modRuntimeOnly "io.wispforest:accessories-common:1.1.0-beta.52+1.21.1"
    modCompileOnly "curse.maven:cobblemon-mega-showdown-1189523:8870188"
    modCompileOnly "dev.architectury:architectury:13.0.8"
}